port: 8080
algorithm: RoundRobin
backend_servers:
  - host: localhost
    port: 8081
    weight: 1
log:
  logger: kafka
  log_path: balancer-logs.json
kafka:
  servers: localhost:9092
  client_id: balancer
  log_topic: balancer-logs
proxies:
  - port: 8080
    host: "example.com"
    locations:
      - path: "/api"
        algorithm: "RoundRobin"
        backend_servers:
          - host: "localhost"
            port: 8001
          - host: "localhost"
            port: 8002
  - port: 9090
    host: "another.com"
    locations:
      - path: "/"
        algorithm: "Random"
        backend_servers:
          - host: "localhost"
            port: 9001
  - port: 9092
    host: "safe.com"
    tls: true
    certificate: certs/example.crt
    certificate_key: certs/example.key
    certificate_ca: certs/example.ca
    locations:
      - path: "/"
        algorithm: "Random"
        backend_servers:
          - host: "localhost"
            port: 9001