port: 8080
algorithm: RoundRobin
backend_servers:
  - host: localhost
    port: 8081
    weight: 1
log:
  logger: kafka
  log_path: balancer-logs.json
kafka:
  servers: localhost:9092
  client_id: balancer
  log_topic: balancer-logs