port: 8080
algorithm: RoundRobin
backend_servers:
  - host: localhost
    port: 8081
    weight: 1
  - host: localhost
    port: 8082
    weight: 1
  - host: localhost
    port: 8083
    weight: 1
log:
  logger: json
  log_path: balancer-logs.json