name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: Download dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Build All Packages
        run: go build ./...
